### PR TITLE
FIX: example to match ansys-sphinx-theme>=0.8

### PR DESCRIPTION
**Pull request by jorgepiloto**
Removes the `get_match_version` function from the multi-version documentation example. This function is already shipped with the latest ansys-sphinx-theme.

### CODE REVIEW

**Review by Revathyvenugopal162 — APPROVED** [review]
LGTM.

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Review by RobPasMue — APPROVED** [review]
LGTM!

**Comment by RobPasMue** [comment]
I just submitted ``linenos`` as an accepted word - this should make CI work

**Comment by jorgepiloto** [comment]
Thank you all for the review. Merging this 🚀

**Pull request merged**
