### PR TITLE
MAINT: replace pyansys.support email with pyansys.core one

### LINKED ISSUE #271: Replace all pyansys.support references with pyansys.core ones
🐞 **Problem**
As suggested internally, let us replace all the references to the `pyansys.support@ansys.com` with the `pyansys.core@ansys.com` email.

### PR DESCRIPTION
**Pull request by jorgepiloto**
Fixes #271 by replacing all the `pyansys.support@ansys.com` email references with `pyansys.core@ansys.com` ones.

### CODE REVIEW

**Review by Revathyvenugopal162 — APPROVED** [review]

**Review by MaxJPRey — APPROVED** [review]
LGTM.

I just hope we won't get too much spam emails on this one 😄 .

**Review by RobPasMue — APPROVED** [review]
LGTM!

**Comment by RobPasMue** [comment]
Us in a few days....

image

**Comment by RobPasMue** [comment]
Ah wait, we are already doing that 😄

**Pull request merged**
